apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-07-31T19:38:38Z"
  generateName: kube-aci-demo-67885558cf-
  labels:
    app: kube-aci-demo
    pod-template-hash: 67885558cf
  name: kube-aci-demo-67885558cf-ml98h
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: kube-aci-demo-67885558cf
    uid: dd1a6fbc-f1c6-4e93-b450-dbd12a55f4ab
  resourceVersion: "323865"
  selfLink: /api/v1/namespaces/default/pods/kube-aci-demo-67885558cf-ml98h
  uid: 55645007-1446-46fb-b469-ac57402f34a5
spec:
  automountServiceAccountToken: false
  containers:
  - image: ubuntu
    imagePullPolicy: Always
    name: kube-aci-demo
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: aks-nodepool1-32733073-vmss000001
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: this-admin
  serviceAccountName: this-admin
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-07-31T19:38:38Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-07-31T19:38:38Z"
    message: 'containers with unready status: [kube-aci-demo]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-07-31T19:38:38Z"
    message: 'containers with unready status: [kube-aci-demo]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-07-31T19:38:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://dc72cf83382fd5e94b0ad4188a60cc771f1ca7deaf1766de36ae8e6824b49e14
    image: ubuntu:latest
    imageID: docker-pullable://ubuntu@sha256:5d1d5407f353843ecf8b16524bc5565aa332e9e6a1297c73a92d3e754b8a636d
    lastState:
      terminated:
        containerID: docker://4675f41641f71aaaed56752493ce88613321e9d75e574c224081be9338c61efe
        exitCode: 0
        finishedAt: "2020-07-31T19:39:31Z"
        reason: Completed
        startedAt: "2020-07-31T19:39:31Z"
    name: kube-aci-demo
    ready: false
    restartCount: 4
    started: false
    state:
      terminated:
        containerID: docker://dc72cf83382fd5e94b0ad4188a60cc771f1ca7deaf1766de36ae8e6824b49e14
        exitCode: 0
        finishedAt: "2020-07-31T19:40:18Z"
        reason: Completed
        startedAt: "2020-07-31T19:40:18Z"
  hostIP: 10.240.0.5
  phase: Running
  podIP: 10.244.2.8
  podIPs:
  - ip: 10.244.2.8
  qosClass: BestEffort
  startTime: "2020-07-31T19:38:38Z"
