apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-vote-back
  template:
    metadata:
      labels:
        app: azure-vote-back
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: disktype
      #           operator: In
      #           values:
      #           - ssd
      # nodeSelector:
      #   "beta.kubernetes.io/os": linux
      containers:
      - name: azure-vote-back
        securityContext:
          runAsUser: 1000
          capabilities:
            add: ["SYS_TIME"]
        image: acrakszshybewpm2dyk.azurecr.io/redis
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 6379
          name: redis
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
spec:
  ports:
  - port: 6379
  selector:
    app: azure-vote-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-vote-front
spec:
  replicas: 5
  selector:
    matchLabels:
      app: azure-vote-front
  template:
    metadata:
      labels:
        app: azure-vote-front
    spec:
      # nodeSelector:
      #   disktype: ssd
      containers:
      - name: azure-vote-front
        image: acrakszshybewpm2dyk.azurecr.io/azure-vote-front:v1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "azure-vote-back"
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: azure-vote-front
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#   selector:
#     app: azure-vote-front
# ---
## Block all incomming traffic to back end service
# kind: NetworkPolicy
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: azure-vote-back-policy
# spec:
#   podSelector:
#     matchLabels:
#       app: azure-vote-back
#   ingress: []
# ---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: azure-vote-back-policy
spec:
  podSelector:
    matchLabels:
      app: azure-vote-back
  policyTypes:
    - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: azure-vote-front
